//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace CDON.Marketplace.Availability {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.8.0/availability", IsNullable=false)]
    public partial class marketplace {
        
        private product[] productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("product")]
        public product[] product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product {
        
        private string idField;
        
        private status statusField;
        
        private bool statusFieldSpecified;
        
        private string stockField;
        
        private marketSE seField;
        
        private marketDK dkField;
        
        private marketNO noField;
        
        private marketFI fiField;
        
        private marketB2BSE b2b_seField;
        
        private marketRakutenFR rakuten_frField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string stock {
            get {
                return this.stockField;
            }
            set {
                this.stockField = value;
            }
        }
        
        /// <remarks/>
        public marketSE se {
            get {
                return this.seField;
            }
            set {
                this.seField = value;
            }
        }
        
        /// <remarks/>
        public marketDK dk {
            get {
                return this.dkField;
            }
            set {
                this.dkField = value;
            }
        }
        
        /// <remarks/>
        public marketNO no {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public marketFI fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
            }
        }
        
        /// <remarks/>
        public marketB2BSE b2b_se {
            get {
                return this.b2b_seField;
            }
            set {
                this.b2b_seField = value;
            }
        }
        
        /// <remarks/>
        public marketRakutenFR rakuten_fr {
            get {
                return this.rakuten_frField;
            }
            set {
                this.rakuten_frField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum status {
        
        /// <remarks/>
        Online,
        
        /// <remarks/>
        Offline,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class marketSE : market {
        
        private deliveryTime deliveryTimeField;
        
        /// <remarks/>
        public deliveryTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class deliveryTime {
        
        private string minField;
        
        private string maxField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string min {
            get {
                return this.minField;
            }
            set {
                this.minField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
        public string max {
            get {
                return this.maxField;
            }
            set {
                this.maxField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketRakutenFR))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketB2BSE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketFI))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketNO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketDK))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketSE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class market {
        
        private status statusField;
        
        /// <remarks/>
        public status status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class marketRakutenFR : market {
        
        private deliveryTime deliveryTimeField;
        
        /// <remarks/>
        public deliveryTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class marketB2BSE : market {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class marketFI : market {
        
        private deliveryTime deliveryTimeField;
        
        /// <remarks/>
        public deliveryTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class marketNO : market {
        
        private deliveryTime deliveryTimeField;
        
        /// <remarks/>
        public deliveryTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class marketDK : market {
        
        private deliveryTime deliveryTimeField;
        
        /// <remarks/>
        public deliveryTime deliveryTime {
            get {
                return this.deliveryTimeField;
            }
            set {
                this.deliveryTimeField = value;
            }
        }
    }
}
