//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace CDON.Marketplace.Price {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price", IsNullable=false)]
    public partial class marketplace {
        
        private product[] productField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("product")]
        public product[] product {
            get {
                return this.productField;
            }
            set {
                this.productField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class product {
        
        private string idField;
        
        private marketSE seField;
        
        private marketDK dkField;
        
        private marketNO noField;
        
        private marketFI fiField;
        
        private marketRakutenFr rakuten_frField;
        
        private marketB2BSE b2b_seField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public marketSE se {
            get {
                return this.seField;
            }
            set {
                this.seField = value;
            }
        }
        
        /// <remarks/>
        public marketDK dk {
            get {
                return this.dkField;
            }
            set {
                this.dkField = value;
            }
        }
        
        /// <remarks/>
        public marketNO no {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public marketFI fi {
            get {
                return this.fiField;
            }
            set {
                this.fiField = value;
            }
        }
        
        /// <remarks/>
        public marketRakutenFr rakuten_fr {
            get {
                return this.rakuten_frField;
            }
            set {
                this.rakuten_frField = value;
            }
        }
        
        /// <remarks/>
        public marketB2BSE b2b_se {
            get {
                return this.b2b_seField;
            }
            set {
                this.b2b_seField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class marketSE : market {
        
        private decimal shippingCostField;
        
        private decimal vatField;
        
        /// <remarks/>
        public decimal shippingCost {
            get {
                return this.shippingCostField;
            }
            set {
                this.shippingCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketB2BSE))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketRakutenFr))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketFI))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketNO))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketDK))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(marketSE))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public abstract partial class market {
        
        private decimal salePriceField;
        
        private decimal originalPriceField;
        
        /// <remarks/>
        public decimal salePrice {
            get {
                return this.salePriceField;
            }
            set {
                this.salePriceField = value;
            }
        }
        
        /// <remarks/>
        public decimal originalPrice {
            get {
                return this.originalPriceField;
            }
            set {
                this.originalPriceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class identity {
        
        private string idField;
        
        private string gtinField;
        
        private string mpnField;
        
        private string skuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string gtin {
            get {
                return this.gtinField;
            }
            set {
                this.gtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string mpn {
            get {
                return this.mpnField;
            }
            set {
                this.mpnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string sku {
            get {
                return this.skuField;
            }
            set {
                this.skuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class marketB2BSE : market {
        
        private decimal vatField;
        
        /// <remarks/>
        public decimal vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class marketRakutenFr : market {
        
        private object shippingCostField;
        
        private decimal vatField;
        
        /// <remarks/>
        public object shippingCost {
            get {
                return this.shippingCostField;
            }
            set {
                this.shippingCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class marketFI : market {
        
        private decimal shippingCostField;
        
        private decimal vatField;
        
        /// <remarks/>
        public decimal shippingCost {
            get {
                return this.shippingCostField;
            }
            set {
                this.shippingCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class marketNO : market {
        
        private decimal shippingCostField;
        
        private decimal vatField;
        
        /// <remarks/>
        public decimal shippingCost {
            get {
                return this.shippingCostField;
            }
            set {
                this.shippingCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://schemas.cdon.com/product/4.0/4.9.0/price")]
    public partial class marketDK : market {
        
        private decimal shippingCostField;
        
        private decimal vatField;
        
        /// <remarks/>
        public decimal shippingCost {
            get {
                return this.shippingCostField;
            }
            set {
                this.shippingCostField = value;
            }
        }
        
        /// <remarks/>
        public decimal vat {
            get {
                return this.vatField;
            }
            set {
                this.vatField = value;
            }
        }
    }
}
